In [1]:
!pip install numpy

In [1]:
import numpy as np


## create array using numpy
## create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
arr2=np.array([1,2,3,4,5])
##arr2.reshape(1,5)
arr2.reshape(5,1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [9]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
## identity matrix

##np.eye([3,3])## wrong hai
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [7]:
## numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([11,22,33,44,55])

## Element wise addition
print("Addition:", arr1+arr2)

## Element wise subtraction
print("Subtraction",arr1-arr2)

##Element wise Multiplication
print("Multiply",arr1*arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [12 24 36 48 60]
Subtraction [-10 -20 -30 -40 -50]
Multiply [ 11  44  99 176 275]
Division: [0.09090909 0.09090909 0.09090909 0.09090909 0.09090909]


In [8]:
np.add(arr1,arr2)

array([12, 24, 36, 48, 60])

In [27]:
## Universal Function

arr=np.array([1,2,3,4,5])
## square root
print(np.sqrt(arr))

## Exponential 

print(np.exp(arr))

## Sine

print(np.sin(arr))

print(np.cos(arr))

## natural log
print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [5]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
print(arr[1:,2:])
print(arr[0])

[[ 7  8]
 [11 12]]
[1 2 3 4]


In [31]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [35]:
print(arr[0][0])
print(arr[0,0])

1
1


In [36]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [40]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [41]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [3]:
## Statistical concepts---Normalization
##to have a mean of 0 and standard deviation of 1
import numpy as np
data=np.array([1,2,3,4,5])

## Calculate mean and variance
mean= np.mean(data)
variance=np.var(data)

## Normalize the data

normalized_data = (data - mean) / np.sqrt(variance)
print("Normalized Data:", normalized_data)

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [4]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [5]:
## Logical Operation

data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [3]:
np.random.randn(2,3)

array([[1.24486602, 0.88568747, 0.94438344],
       [0.92461576, 0.07695062, 1.55039537]])

In [10]:
a=np.sum(arr)
print(a)

78
