# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
import numpy as np

In [2]:
arr1=np.array([5,5])
print(arr1)

[5 5]


In [13]:
arr=np.random.randint(1,100,(5,5))
print(arr)

[[51 10 40 50 71]
 [57 45 22 60 14]
 [17 48 40 51 25]
 [83 67 32 42 87]
 [12  6 85 77  4]]


In [15]:
arr[0:,2]=1
print(arr)

[[51 10  1 50 71]
 [57 45  1 60 14]
 [17 48  1 51 25]
 [83 67  1 42 87]
 [12  6  1 77  4]]


In [39]:
arr=np.arange(1,17).reshape(4,4)
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [40]:
np.fill_diagonal(arr,0)
print(arr)


[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [41]:
arr=np.arange(1,37).reshape(6,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [43]:
print(arr[3:5,2:4])

[[21 22]
 [27 28]]


In [4]:
arr=np.random.randint(1,25,(5,5))
print(arr)

[[23 23 16  3  6]
 [ 2  8 14 16 21]
 [21 16  7 15 23]
 [ 2 18 15  6  2]
 [15  1  7 13 20]]


In [10]:
print(arr[0:,:1])
print(arr[1:,:0])

[[23]
 [ 2]
 [21]
 [ 2]
 [15]]
[]


In [ ]:
arr1=np.random.randint(1,99,(3,4))
arr2=np.random.randint(1,99,(3,4))
print(arr1)
print(arr2)



[[80  1 12 12]
 [75 56 70 23]
 [44 80  2 55]]
[[40 56 50 11]
 [76 49 56  8]
 [ 4 20 87 75]]


In [9]:
print(arr1+arr2)

[[120  57  62  23]
 [151 105 126  31]
 [ 48 100  89 130]]


In [10]:
print(arr1-arr2)

[[ 40 -55 -38   1]
 [ -1   7  14  15]
 [ 40  60 -85 -20]]


In [11]:
print(arr1*arr2)

[[3200   56  600  132]
 [5700 2744 3920  184]
 [ 176 1600  174 4125]]


In [12]:
print(arr1/arr2)

[[ 2.          0.01785714  0.24        1.09090909]
 [ 0.98684211  1.14285714  1.25        2.875     ]
 [11.          4.          0.02298851  0.73333333]]


In [20]:
arr=np.arange(1,17).reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [22]:
row_sum=np.sum(arr,axis=1)
print(row_sum)

[10 26 42 58]


In [23]:
coulmn_sum=np.sum(arr,axis=0)
print(coulmn_sum)

[28 32 36 40]


In [27]:
##1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

arr=np.random.randint(1,99,(5,5))
print(arr)
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))

[[83 31 36 19 66]
 [72 91 90  2 84]
 [58 40 83 16  5]
 [81 14 85 34 67]
 [23 78  2 17 47]]
48.96
47.0
937.4784000000001
30.61826905623504


In [30]:
data=np.arange(1,10).reshape(3,3)
print(data)

## Calculate mean and variance
mean= np.mean(data)
variance=np.var(data)

## Normalize the data

normalized_data = (data - mean) / np.sqrt(variance)
print("Normalized Data:", normalized_data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Data: [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [42]:
arr1=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
arr2=np.array([1,2,3])
print(arr2)

[1 2 3]


In [43]:
result=arr1+arr2
print(result)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [44]:
arr=np.random.randint(1,99,(3,3))
print(arr)

[[51 37 96]
 [93 23 58]
 [70 60 88]]


In [48]:
## determinant
det=np.linalg.det(arr)
print(det)

## inverse

inverse=np.linalg.inv(arr)
print(inverse)

## eigen

eigen=np.linalg.eig(arr)
print(eigen)

154275.9999999999
[[-0.00943763  0.01623065 -0.00040188]
 [-0.02673131 -0.01446758  0.03869688]
 [ 0.0257331  -0.00304649 -0.01470093]]
EigResult(eigenvalues=array([196.33762995 +0.j        , -17.16881497+22.15853503j,
       -17.16881497-22.15853503j]), eigenvectors=array([[ 0.55952054+0.j        , -0.17542224+0.38831467j,
        -0.17542224-0.38831467j],
       [ 0.51696533+0.j        ,  0.80203596+0.j        ,
         0.80203596-0.j        ],
       [ 0.64782992+0.j        , -0.27418217-0.31622969j,
        -0.27418217+0.31622969j]]))


In [54]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.random.randint(1,99,(3,3))
print(arr1)
print(arr2)


matrix_mul=np.dot(arr1,arr2)
print(matrix_mul)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[68 83  4]
 [78 76 46]
 [81 22 24]]
[[ 467  301  168]
 [1148  844  390]
 [1829 1387  612]]
